#########
#
# Build the various demos
#
#
BIN-y += fire
BIN-y += life
BIN-y += cube-life
BIN-y += matrix-test
BIN-y += identify

fire.srcs += fire.c
life.srcs += life.c
identify.srcs += identify-main.c
cube-life.srcs += cube-life.c
matrix-test.srcs += matrix-test-main.c

include ../../Makefile.common

